import type { CourseModule } from '../../types';

export const phonicsModule: CourseModule = {
  id: 'phonics',
  title: 'Sound Safari',
  planet: 'Echo Planet',
  mission: 'Teach Zibi the Earth words that wake up the ship.',
  colorClass: 'yellow',
  lessons: [
    {
      id: 'word-sun',
      moduleId: 'phonics',
      type: 'phonics',
      title: 'Star Sun ⭐️',
      storyPrompt: 'Say "sun" to wake up Zibi\'s tickly antenna. Try it like the bright star in the sky!',
      rewardName: 'Antenna Star Seed',
      targetText: 'sun',
      displayText: 'sun',
      phonicsParts: ['sun'],
      successMatches: ['sun', 'son'],
      coachPrompt: 'Say the word "sun" clearly — teeth close, air sliding out like a snake.',
      retryPrompt: 'Try saying "sun" again — start with a soft /s/ sound.',
      repairPart: 'antenna',
    },
    {
      id: 'word-moon',
      moduleId: 'phonics',
      type: 'phonics',
      title: 'Moon Hum 🌙',
      storyPrompt: 'Say "moon" to spin the moon engine. Hum it with your lips together!',
      rewardName: 'Engine Star Seed',
      targetText: 'moon',
      displayText: 'moon',
      phonicsParts: ['moon'],
      successMatches: ['moon', 'moons', 'moo'],
      coachPrompt: 'Say the word "moon" — close your lips and hum through your nose.',
      retryPrompt: 'Try saying "moon" again — start with a humming /m/ sound.',
      repairPart: 'engine',
    },
    {
      id: 'word-apple',
      moduleId: 'phonics',
      type: 'phonics',
      title: 'Apple Word 🍎',
      storyPrompt: 'Say "apple" to open the ship window. Open your mouth wide like you\'re biting an apple!',
      rewardName: 'Window Star Seed',
      targetText: 'apple',
      displayText: 'apple',
      phonicsParts: ['ap', 'ple'],
      successMatches: ['apple', 'apples'],
      coachPrompt: 'Say the word "apple" — open your mouth wide for that short vowel sound.',
      retryPrompt: 'Try saying "apple" again — open wide for the first sound.',
      repairPart: 'window dome',
    },
    {
      id: 'word-tap',
      moduleId: 'phonics',
      type: 'phonics',
      title: 'Tap Word ⏰',
      storyPrompt: 'Say "tap" to press the launch button. Quick tongue tap!',
      rewardName: 'Button Star Seed',
      targetText: 'tap',
      displayText: 'tap',
      phonicsParts: ['tap'],
      successMatches: ['tap', 'tapped'],
      coachPrompt: 'Say the word "tap" — touch your tongue behind your top teeth for a quick /t/.',
      retryPrompt: 'Try saying "tap" again — quick tongue tap at the start.',
      repairPart: 'launch button',
    },
    {
      id: 'word-pop',
      moduleId: 'phonics',
      type: 'phonics',
      title: 'Pop Word 🫧',
      storyPrompt: 'Say "pop" to open the fuel pod. Pop your lips with a puff of air!',
      rewardName: 'Fuel Star Seed',
      targetText: 'pop',
      displayText: 'pop',
      phonicsParts: ['pop'],
      successMatches: ['pop', 'popped'],
      coachPrompt: 'Say the word "pop" — press your lips together, then pop them open.',
      retryPrompt: 'Try saying "pop" again — press your lips, then let the air pop.',
      repairPart: 'fuel pod',
    },
    {
      id: 'word-sat',
      moduleId: 'phonics',
      type: 'phonics',
      title: 'Ship Seat 🚀',
      storyPrompt: 'Blend the sounds together to say "sat". Slide them into one word!',
      rewardName: 'Seat Star Seed',
      targetText: 'sat',
      displayText: 'sat',
      phonicsParts: ['s', 'a', 't'],
      successMatches: ['sat', 'satt', 'sate', 'sad', 'set', 'sit', 'sot', 'that', 'said'],
      coachPrompt: 'Slide the sounds together: s... a... t → sat!',
      retryPrompt: 'Say "sat". Start with s, open to a, then tap t.',
      repairPart: 'seat belt',
    },
    {
      id: 'word-mat',
      moduleId: 'phonics',
      type: 'phonics',
      title: 'Landing Mat 🛬',
      storyPrompt: 'Blend the sounds together to say "mat". Slide them into one word!',
      rewardName: 'Landing Star Seed',
      targetText: 'mat',
      displayText: 'mat',
      phonicsParts: ['m', 'a', 't'],
      successMatches: ['mat', 'matt', 'mate', 'mad', 'met', 'map', 'man', 'mass', 'mats', 'that'],
      coachPrompt: 'Slide the sounds together: m... a... t → mat!',
      retryPrompt: 'Say "mat". Hum m, open to a, then tap t.',
      repairPart: 'landing mat',
    },
    {
      id: 'word-pat',
      moduleId: 'phonics',
      type: 'phonics',
      title: 'Repair Pat 👋',
      storyPrompt: 'Blend the sounds together to say "pat". Slide them into one word!',
      rewardName: 'Hull Star Seed',
      targetText: 'pat',
      displayText: 'pat',
      phonicsParts: ['p', 'a', 't'],
      successMatches: ['pat', 'patt', 'pad', 'pet', 'pit', 'pot', 'pats', 'pack', 'path', 'that'],
      coachPrompt: 'Slide the sounds together: p... a... t → pat!',
      retryPrompt: 'Say "pat". Pop p, open to a, then tap t.',
      repairPart: 'ship hull',
    },
  ],
};
