import type { CourseModule } from '../types';

export const phonicsModule: CourseModule = {
  id: 'phonics',
  title: 'Sound Safari',
  planet: 'Echo Planet',
  mission: 'Teach Zibi the Earth sounds that wake up words.',
  colorClass: 'yellow',
  lessons: [
    {
      id: 'sound-s',
      moduleId: 'phonics',
      type: 'phonics',
      kind: 'sound',
      title: 'Star Air',
      storyPrompt: 'Zibi found the ship antenna. It glows when it hears a long s sound.',
      rewardName: 'Antenna Star Seed',
      targetText: 's',
      displayText: 'S',
      phonicsParts: ['ssss'],
      successMatches: ['s', 'ess', 'sss', 'say', 'sea', 'see'],
      expectedSoundClass: 'hissy',
      coachPrompt: 'Teeth close. Let air slide out.',
      retryPrompt: 'Try a long s sound.',
      repairPart: 'antenna',
    },
    {
      id: 'sound-m',
      moduleId: 'phonics',
      type: 'phonics',
      kind: 'sound',
      title: 'Moon Hum',
      storyPrompt: 'The moon engine needs a gentle mmm hum.',
      rewardName: 'Engine Star Seed',
      targetText: 'm',
      displayText: 'M',
      phonicsParts: ['mmmm'],
      successMatches: ['m', 'em', 'mmm', 'mom', 'hum'],
      expectedSoundClass: 'open',
      coachPrompt: 'Lips together. Let the sound buzz.',
      retryPrompt: 'Close your lips and hum mmmm.',
      repairPart: 'engine',
    },
    {
      id: 'sound-a',
      moduleId: 'phonics',
      type: 'phonics',
      kind: 'sound',
      title: 'Open Air',
      storyPrompt: 'Zibi opens the ship window to catch the short a sound.',
      rewardName: 'Window Star Seed',
      targetText: 'a',
      displayText: 'A',
      phonicsParts: ['aaa'],
      successMatches: ['a', 'ah', 'aa', 'at'],
      expectedSoundClass: 'open',
      coachPrompt: 'Open your mouth. Short sound: aaa.',
      retryPrompt: 'Open wide and say aaa.',
      repairPart: 'window dome',
    },
    {
      id: 'sound-t',
      moduleId: 'phonics',
      type: 'phonics',
      kind: 'sound',
      title: 'Tap Button',
      storyPrompt: 'The launch button listens for one quick t tap.',
      rewardName: 'Button Star Seed',
      targetText: 't',
      displayText: 'T',
      phonicsParts: ['t'],
      successMatches: ['t', 'tea', 'tee', 'to'],
      expectedSoundClass: 'pop',
      coachPrompt: 'Tongue taps up top. Make it quick.',
      retryPrompt: 'Tap the sound: t.',
      repairPart: 'launch button',
    },
    {
      id: 'sound-p',
      moduleId: 'phonics',
      type: 'phonics',
      kind: 'sound',
      title: 'Pop Pod',
      storyPrompt: 'A fuel pod pops open when it hears p.',
      rewardName: 'Fuel Star Seed',
      targetText: 'p',
      displayText: 'P',
      phonicsParts: ['p'],
      successMatches: ['p', 'pea', 'pee', 'pa'],
      expectedSoundClass: 'pop',
      coachPrompt: 'Lips pop open. Tiny burst of air.',
      retryPrompt: 'Pop your lips: p.',
      repairPart: 'fuel pod',
    },
    {
      id: 'word-sat',
      moduleId: 'phonics',
      type: 'phonics',
      kind: 'word',
      title: 'Ship Seat',
      storyPrompt: 'Zibi needs to sit safely before launch.',
      rewardName: 'Seat Star Seed',
      targetText: 'sat',
      displayText: 'SAT',
      phonicsParts: ['s', 'a', 't'],
      successMatches: ['sat'],
      coachPrompt: 'Slide the sounds together: s-a-t.',
      retryPrompt: 'Start with ssss, then aaa, then t.',
      repairPart: 'seat belt',
    },
    {
      id: 'word-mat',
      moduleId: 'phonics',
      type: 'phonics',
      kind: 'word',
      title: 'Landing Mat',
      storyPrompt: 'The ship needs a soft landing mat.',
      rewardName: 'Landing Star Seed',
      targetText: 'mat',
      displayText: 'MAT',
      phonicsParts: ['m', 'a', 't'],
      successMatches: ['mat'],
      coachPrompt: 'Buzz, open, tap: m-a-t.',
      retryPrompt: 'Try mmmm, aaa, t.',
      repairPart: 'landing mat',
    },
    {
      id: 'word-pat',
      moduleId: 'phonics',
      type: 'phonics',
      kind: 'word',
      title: 'Repair Pat',
      storyPrompt: 'Give the ship a gentle repair pat.',
      rewardName: 'Hull Star Seed',
      targetText: 'pat',
      displayText: 'PAT',
      phonicsParts: ['p', 'a', 't'],
      successMatches: ['pat'],
      coachPrompt: 'Pop, open, tap: p-a-t.',
      retryPrompt: 'Try p, aaa, t.',
      repairPart: 'ship hull',
    },
  ],
};
