import type { CourseModule } from '../../types';

export const phonicsModule: CourseModule = {
  id: 'phonics',
  title: 'Sound Safari',
  planet: 'Echo Planet',
  mission: 'Teach Zibi the Earth sounds that wake up words.',
  colorClass: 'yellow',
  lessons: [
    {
      id: 'sound-s',
      moduleId: 'phonics',
      type: 'phonics',
      kind: 'sound',
      title: 'Star Air ⭐️',
      storyPrompt: 'Make the /s/ sound to wake up Zibi\'s tickly antenna.',
      rewardName: 'Antenna Star Seed',
      targetText: 's',
      displayText: '/s/',
      phonicsParts: ['/s/'],
      successMatches: ['s', 'ess', 'sss', 'snake', 'star', 'sun', 'sip'],
      expectedSoundClass: 'hissy',
      coachPrompt: 'Teeth close. Let air slide out like a snake: ssss.',
      retryPrompt: 'Try the /s/ sound again. Long air, no voice.',
      repairPart: 'antenna',
    },
    {
      id: 'sound-m',
      moduleId: 'phonics',
      type: 'phonics',
      kind: 'sound',
      title: 'Moon Hum 🌙',
      storyPrompt: 'Make the /m/ sound to spin the moon engine.',
      rewardName: 'Engine Star Seed',
      targetText: 'm',
      displayText: '/m/',
      phonicsParts: ['/m/'],
      successMatches: ['m', 'em', 'mmm', 'mom', 'hum', 'moon', 'mat'],
      expectedSoundClass: 'open',
      coachPrompt: 'Lips together. Hum through your nose: mmmm.',
      retryPrompt: 'Try the /m/ sound again. Lips closed, gentle hum.',
      repairPart: 'engine',
    },
    {
      id: 'sound-a',
      moduleId: 'phonics',
      type: 'phonics',
      kind: 'sound',
      title: 'Open Air 🐥',
      storyPrompt: 'Make the short /ă/ sound to open the ship window.',
      rewardName: 'Window Star Seed',
      targetText: 'a',
      displayText: '/ă/',
      phonicsParts: ['/ă/'],
      successMatches: ['a', 'ah', 'aa', 'at', 'apple', 'cat', 'sat', 'mat', 'pat'],
      expectedSoundClass: 'open',
      coachPrompt: 'Open wide. Short vowel sound: /ă/, like apple or cat.',
      retryPrompt: 'Try the short /ă/ sound again. Open mouth, quick voice.',
      repairPart: 'window dome',
    },
    {
      id: 'sound-t',
      moduleId: 'phonics',
      type: 'phonics',
      kind: 'sound',
      title: 'Tap Button ⏰',
      storyPrompt: 'Make the /t/ sound to tap the launch button.',
      rewardName: 'Button Star Seed',
      targetText: 't',
      displayText: '/t/',
      phonicsParts: ['/t/'],
      successMatches: ['t', 'tea', 'tee', 'tap', 'top', 'at', 'sat', 'mat', 'pat'],
      expectedSoundClass: 'pop',
      coachPrompt: 'Tongue taps behind your teeth. Make one quick /t/.',
      retryPrompt: 'Try the /t/ sound again. Quick tongue tap.',
      repairPart: 'launch button',
    },
    {
      id: 'sound-p',
      moduleId: 'phonics',
      type: 'phonics',
      kind: 'sound',
      title: 'Pop Pod 🫧',
      storyPrompt: 'Make the /p/ sound to pop open the fuel pod.',
      rewardName: 'Fuel Star Seed',
      targetText: 'p',
      displayText: '/p/',
      phonicsParts: ['/p/'],
      successMatches: ['p', 'pea', 'pa', 'pop', 'pod', 'pat', 'up', 'cap'],
      expectedSoundClass: 'pop',
      coachPrompt: 'Lips together, then pop them open with air: /p/.',
      retryPrompt: 'Try the /p/ sound again. Quiet lip pop.',
      repairPart: 'fuel pod',
    },
    {
      id: 'word-sat',
      moduleId: 'phonics',
      type: 'phonics',
      kind: 'word',
      title: 'Ship Seat 🚀',
      storyPrompt: 'Blend /s/ /ă/ /t/ to say sat.',
      rewardName: 'Seat Star Seed',
      targetText: 'sat',
      displayText: 'sat',
      phonicsParts: ['/s/', '/ă/', '/t/'],
      successMatches: ['sat', 'satt', 'sate', 'sad', 'set', 'sit'],
      coachPrompt: 'Slide the sounds together: /s/ /ă/ /t/, sat.',
      retryPrompt: 'Say sat. Start with /s/, open to /ă/, then tap /t/.',
      repairPart: 'seat belt',
    },
    {
      id: 'word-mat',
      moduleId: 'phonics',
      type: 'phonics',
      kind: 'word',
      title: 'Landing Mat 🛬',
      storyPrompt: 'Blend /m/ /ă/ /t/ to say mat.',
      rewardName: 'Landing Star Seed',
      targetText: 'mat',
      displayText: 'mat',
      phonicsParts: ['/m/', '/ă/', '/t/'],
      successMatches: ['mat', 'matt', 'mate', 'mad', 'met'],
      coachPrompt: 'Slide the sounds together: /m/ /ă/ /t/, mat.',
      retryPrompt: 'Say mat. Hum /m/, open to /ă/, then tap /t/.',
      repairPart: 'landing mat',
    },
    {
      id: 'word-pat',
      moduleId: 'phonics',
      type: 'phonics',
      kind: 'word',
      title: 'Repair Pat 👋',
      storyPrompt: 'Blend /p/ /ă/ /t/ to say pat.',
      rewardName: 'Hull Star Seed',
      targetText: 'pat',
      displayText: 'pat',
      phonicsParts: ['/p/', '/ă/', '/t/'],
      successMatches: ['pat', 'patt', 'pad', 'pet', 'pit'],
      coachPrompt: 'Slide the sounds together: /p/ /ă/ /t/, pat.',
      retryPrompt: 'Say pat. Pop /p/, open to /ă/, then tap /t/.',
      repairPart: 'ship hull',
    },
  ],
};
