import type { CourseModule } from '../types';
import { phonicsModule } from './modules/phonics';
import { writingModule } from './modules/writing';

const lettersModule: CourseModule = {
  id: 'letters',
  title: 'Letter Lagoon',
  planet: 'Glow Letter Lagoon',
  mission: 'Match Earth sounds to big bright letters.',
  colorClass: 'blue',
  lessons: [
    {
      id: 'letter-s',
      moduleId: 'letters',
      type: 'letter-choice',
      title: 'Find Snakey Sound',
      storyPrompt: 'Zibi hears a snakey ssss sound! Help him find the picture that starts with that sound.',
      rewardName: 'Star Trail Seed',
      prompt: 'Which picture starts with the ssss sound?',
      correctChoiceId: 'sun',
      successPrompt: 'Hooray! Sun starts with S!',
      retryPrompt: 'Look for the bright round thing in the sky that starts with ssss.',
      choices: [
        { id: 'sun', label: 'Sun', helper: 'ssss-un!', art: 'sun' },
        { id: 'moon', label: 'Moon', helper: 'mmmm-oon!', art: 'moon' },
        { id: 'leaf', label: 'Leaf', helper: 'llll-eaf!', art: 'leaf' },
      ],
    },
    {
      id: 'letter-m',
      moduleId: 'letters',
      type: 'letter-choice',
      title: 'Find Humming Sound',
      storyPrompt: 'The night garden hums mmmm! Help Zibi find the humming picture!',
      rewardName: 'Moon Garden Seed',
      prompt: 'Which picture starts with the mmmm sound?',
      correctChoiceId: 'moon',
      successPrompt: 'Yes! Moon starts with M!',
      retryPrompt: 'Look for the glowing shape that shines at night: mmmm.',
      choices: [
        { id: 'moon', label: 'Moon', helper: 'mmmm-oon!', art: 'moon' },
        { id: 'star', label: 'Star', helper: 'ssss-tar!', art: 'star' },
        { id: 'rocket', label: 'Rocket', helper: 'rrrr-ocket!', art: 'rocket' },
      ],
    },
    {
      id: 'letter-p',
      moduleId: 'letters',
      type: 'letter-choice',
      title: 'Find Popping Sound',
      storyPrompt: "Listen for the popping pppp sound! Let's choose the correct starting picture!",
      rewardName: 'Pop Star Seed',
      prompt: 'Which picture starts with the pppp sound?',
      correctChoiceId: 'planet',
      successPrompt: 'Yay! Planet starts with P!',
      retryPrompt: 'Look for the big round space ball: pppp-lanet.',
      choices: [
        { id: 'planet', label: 'Planet', helper: 'pppp-lanet!', art: 'planet' },
        { id: 'jump', label: 'Jump', helper: 'jjjj-ump!', art: 'jump' },
        { id: 'ship', label: 'Ship', helper: 'ssss-hip!', art: 'ship' },
      ],
    },
    {
      id: 'letter-match-a',
      moduleId: 'letters',
      type: 'letter-choice',
      title: 'Big and Little A',
      storyPrompt: 'Zibi finds a big sister letter A and needs to find her little brother letter helper.',
      rewardName: 'Alphabet Seed',
      prompt: 'Which little letter matches the big sister A?',
      correctChoiceId: 'a',
      successPrompt: 'Fantastic! A and a are letter buddies!',
      retryPrompt: 'Find the round little a with a short tail.',
      choices: [
        { id: 'o', label: 'o', helper: 'little o', art: 'planet' },
        { id: 'a', label: 'a', helper: 'little a', art: 'leaf' },
        { id: 'p', label: 'p', helper: 'little p', art: 'rocket' },
      ],
    },
    {
      id: 'letter-match-s',
      moduleId: 'letters',
      type: 'letter-choice',
      title: 'Big and Little S',
      storyPrompt: 'Zibi has a big curvy S. Help him match it with the little brother letter!',
      rewardName: 'Super Star Seed',
      prompt: 'Which little letter matches the big sister S?',
      correctChoiceId: 's',
      successPrompt: 'Super! S and s are curvy snake partners!',
      retryPrompt: 'Find the curvy little s.',
      choices: [
        { id: 's', label: 's', helper: 'little s', art: 'star' },
        { id: 't', label: 't', helper: 'little t', art: 'path' },
        { id: 'm', label: 'm', helper: 'little m', art: 'moon' },
      ],
    },
  ],
};

const grammarModule: CourseModule = {
  id: 'grammar',
  title: 'Tiny Talk Town',
  planet: 'Sentence Town',
  mission: 'Help Zibi build tiny Earth ideas with pictures.',
  colorClass: 'pink',
  lessons: [
    {
      id: 'grammar-noun',
      moduleId: 'grammar',
      type: 'grammar-choice',
      title: 'Naming Word (Noun)',
      storyPrompt: 'Zibi sees a floating space object. In Earth talk, the name of a thing is called a Noun!',
      rewardName: 'Naming Seed',
      prompt: 'Which word is the name of a thing (Noun)?',
      correctChoiceId: 'rocket',
      successPrompt: 'Perfect! Rocket is a thing word (Noun)!',
      retryPrompt: 'Look for the shiny flying ship.',
      choices: [
        { id: 'rocket', label: 'Rocket', helper: 'A flying ship!', art: 'rocket' },
        { id: 'jump', label: 'Jump', helper: 'An action word!', art: 'jump' },
        { id: 'bright', label: 'Bright', helper: 'Descriptive word!', art: 'sun' },
      ],
    },
    {
      id: 'grammar-action',
      moduleId: 'grammar',
      type: 'grammar-choice',
      title: 'Action Word (Verb)',
      storyPrompt: 'Zibi wants to bounce up and down! Action words are called Verbs.',
      rewardName: 'Action Seed',
      prompt: 'Which word shows an action (Verb)?',
      correctChoiceId: 'jump',
      successPrompt: 'Whoosh! Jump is a doing word (Verb)!',
      retryPrompt: 'Find the word that shows moving.',
      choices: [
        { id: 'ship', label: 'Ship', helper: 'A space thing!', art: 'ship' },
        { id: 'jump', label: 'Jump', helper: 'An active bounce!', art: 'jump' },
        { id: 'green', label: 'Green', helper: 'A color!', art: 'leaf' },
      ],
    },
    {
      id: 'grammar-sentence',
      moduleId: 'grammar',
      type: 'sentence-build',
      title: 'First Message',
      storyPrompt: "Zibi wants to tell you he can bounce! Let's build his sentence.",
      rewardName: 'Message Seed',
      prompt: 'Tap the word blocks in order to say "Zibi can fly!"',
      tiles: ['fly', 'Zibi', 'can'],
      correctSequence: ['Zibi', 'can', 'fly'],
      successPrompt: 'Amazing! "Zibi can fly!" is a real sentence!',
      retryPrompt: 'Start with Zibi, then can, then fly.',
    },
    {
      id: 'grammar-sentence-2',
      moduleId: 'grammar',
      type: 'sentence-build',
      title: 'Space Sight',
      storyPrompt: "Let's build a sentence to show what Zibi sees in the sky!",
      rewardName: 'Sky Seed',
      prompt: 'Tap the word blocks to make "Zibi sees the moon!"',
      tiles: ['sees', 'moon', 'the', 'Zibi'],
      correctSequence: ['Zibi', 'sees', 'the', 'moon'],
      successPrompt: 'Brilliant! "Zibi sees the moon!" is a perfect sentence!',
      retryPrompt: 'Tap who first (Zibi), then sees, then the, then moon.',
    },
  ],
};

export const COURSE_MODULES: CourseModule[] = [
  phonicsModule,
  lettersModule,
  grammarModule,
  writingModule,
];
